### ISSUE TITLE
Upgrade to Jetty 7.x

### ISSUE THREAD

**Issue by vitalyper** [mmcgrana/ring#40]
Any plans to upgrade to jetty 7.x?

**Comment by mrh0057** [comment]
There is a jetty 7 adapter available here: https://github.com/jalpedersen/ring-jetty7-adapter

**Comment by weavejester** [comment]
Not for Ring 1.0, but it's a possibility for Ring 1.1.

See here for the discussion on Ring 1.1 features: https://groups.google.com/forum/#!topic/ring-clojure/Ys3MtCe4xow

**Comment by weavejester** [comment]
The master branch is now on Jetty 7.
