### ISSUE TITLE
wrap-keyword-params doesn't work with wrap-multipart-params

### ISSUE THREAD

**Issue by tomassedovic** [mmcgrana/ring#43]
It seems that the keyword-params middleware doesn't accept a map with keys that are keywords instead of strings.

Multipart-params produces such a map on file upload. The input's name is passed as a string, but the hash with the file metadata contains keywords `:size`, `:tempfile`, etc.

**Comment by weavejester** [comment]
This should now be fixed in version 1.0.0-RC4. Thanks for reporting the issue!
