### ISSUE TITLE
Clean up ring.handler.dump

### ISSUE THREAD

**Issue by weavejester** [mmcgrana/ring#54]
- Inline CSS should be in a resource
- Use new Hiccup functions like `html5`
- Update the set of ring keys.

**Comment by shanmuha** [comment]
Fixed the described issues - moved private resource-style function to ring.util.resource for getting resource files as stylesheets.
dump would also return html5 now.
Ring keys updated to added ssl-client-cert as well.

**Comment by shanmuha** [comment]
opened pul request#66 for the code.
