### ISSUE TITLE
Cookies support clj-time intervals and dates

### ISSUE THREAD

**Issue by weavejester** [mmcgrana/ring#55]
In `ring.middleware.wrap-cookies`:
- The `:max-age` key should support JodaTime Intervals (via clj-time)
- The `:expires` key should support JodaTime DateTimes and Java Dates

Existing Ring 1.0 behaviour should not be affected (i.e. `:max-age` should handle an integer, etc.)

(See: https://github.com/seancorfield/clj-time)

**Comment by KushalP** [comment]
The only thing left before my work so far (see commits referenced above) can be merged in is for checks to test whether `:max-age` and `:expires` only accept `Interval` and `DateTime` objects, respectively.

How should I notify the user that they're providing incorrect data as input? What's the preferred way?

**Comment by weavejester** [comment]
A precondition would probably be the best solution.

**Comment by KushalP** [comment]
How should that be laid out? I was thinking about something like this:

```
:pre (if (and (= key :max-size) (= value (str value))
         true
         (instance? Interval value))
```

But are there better ways of laying this out?

**Comment by weavejester** [comment]
The `valid-attr?` function is already used to validate the attribute via a pre-condition. You can extend the function with a conditional and more tests.
