### ISSUE TITLE
Implementation of `temp-file-store` creates too many futures

### ISSUE THREAD

**Issue by alexott** [mmcgrana/ring#74]
Implementation of `temp-file-store` in the `ring.middleware.multipart-params.temp-file` creates too many futures objects and this leads to too many threads running on web services that handles many multipart uploads...

P.S. I'll try to refactor code to use single expiration thread or something like...

**Comment by weavejester** [comment]
The canonical repository is now at: https://github.com/ring-clojure/ring

Issues should be raised there.

In this case, it looks like the logic for the store is wrong; the expiration thread should only be created once, but it has been placed inside the storage function, not outside it.

**Comment by alexott** [comment]
Oops, I'm sorry - I forgot about ring organization - I will create issue there...
