### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by ghost** [mmcgrana/ring#75]
Just a doc error in https://github.com/mmcgrana/ring/wiki/Sessions

```
(def app
  (wrap-session handler {:cookie-attrs {:max-age 3600}))
```

Forgot a }

**Comment by weavejester** [comment]
You know that wikis are publicly editable, right? You don't need to open an issue for a typo - just edit the page and fix it right there. Also, the canonical Ring repository is at https://github.com/ring-clojure/ring.

**Comment by ghost** [comment]
I have actually never thought about how to edit a wiki.

I'll just edit it next time directly :)
