### ISSUE TITLE
How to access Jetty request object

### ISSUE THREAD

**Issue by ghost** [mmcgrana/ring#77]
I need to use http://jetty.codehaus.org/jetty/jetty-6/apidocs/org/mortbay/jetty/Request.html#getLocale() to get the locale from the Accept-Language string.

How do I access the Jetty request directly for this?

**Comment by weavejester** [comment]
Please use the Google group for questions and leave the github issue tracker for issues only.

Also, if you are going to open issues, please use the canonical ring repository at github.com/ring-clojure/ring

**Comment by ghost** [comment]
Okay sorry.
