### ISSUE TITLE
The middleware wrap-head makes Content-Length always be 0

### ISSUE THREAD

**Issue by aviflax** [mmcgrana/ring#81]
Because it sets :body to nil, and :body is used to set Content-Length.

**Comment by weavejester** [comment]
Please use the official repository at https://github.com/ring-clojure/ring to report issues. This repository is deprecated.

**Comment by aviflax** [comment]
Will do, thanks.

Suggestion: there are 3 open issues remaining in this repo; at quick glance they give the impression that it’s still active. You might want to close those remaining issues and open a new one entitled “THIS REPO IS DEPRECATED”, just to prevent this from happening again.

**Comment by weavejester** [comment]
Good point about the issues. I've closed them. However, I don't really want to open a new issue just to note that the repository is deprecated. The big notice in the readme should really be enough.

**Comment by aviflax** [comment]
Makes sense, but FYI with the new GitHub repo redesign the notice isn’t above the fold on my 13" laptop:

![screen shot 2013-06-24 at 17 42 52 pm](https://f.cloud.github.com/assets/141844/699117/2a88f8c6-dd17-11e2-8dc8-fe9615eaa724.png)
