### ISSUE TITLE
*read-eval* false?

### ISSUE THREAD

**Issue by txrev319** [mmcgrana/ring#82]
At https://github.com/mmcgrana/ring/blob/master/ring-core/src/ring/middleware/session/cookie.clj#L92

should there be a

(binding [_read-eval_ false] ) ?

Otherwise, it seems -- suppose some other vulnerability allowed the AES key to leak -- then we suddenly have the situation where the client can do arbitrary code execution by read macros?

**Comment by weavejester** [comment]
You're right, but this bug has been fixed. You're looking at an old repository. Here's the latest code:

https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session/cookie.clj#L81

**Comment by txrev319** [comment]
Thanks for the response.

I apologize for the false positive. (I'm not sure how I ended up reading a
old version of the code).
